from PyQt5.QtWidgets import QApplication, QTableWidgetItem, QMainWindow
from PyQt5 import QtCore, QtWidgets


class Ui_add_coffee(object):
    def setupUi(self, add_coffee):
        add_coffee.setObjectName("add_coffee")
        add_coffee.resize(401, 311)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(add_coffee)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 60, 251, 22))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.roastlayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.roastlayout.setContentsMargins(0, 0, 0, 0)
        self.roastlayout.setObjectName("roastlayout")
        self.roastlabel = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.roastlabel.setObjectName("roastlabel")
        self.roastlayout.addWidget(self.roastlabel)
        self.roastinput = QtWidgets.QSpinBox(self.horizontalLayoutWidget_3)
        self.roastinput.setObjectName("roastinput")
        self.roastlayout.addWidget(self.roastinput)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(add_coffee)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 90, 251, 22))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.seedlayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.seedlayout.setContentsMargins(0, 0, 0, 0)
        self.seedlayout.setObjectName("seedlayout")
        self.seedlabel = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.seedlabel.setObjectName("seedlabel")
        self.seedlayout.addWidget(self.seedlabel)
        self.seedinput = QtWidgets.QSpinBox(self.horizontalLayoutWidget_4)
        self.seedinput.setMaximum(1)
        self.seedinput.setObjectName("seedinput")
        self.seedlayout.addWidget(self.seedinput)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(add_coffee)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 120, 251, 22))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.desclayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.desclayout.setContentsMargins(0, 0, 0, 0)
        self.desclayout.setObjectName("desclayout")
        self.desclabel = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.desclabel.setObjectName("desclabel")
        self.desclayout.addWidget(self.desclabel)
        self.descinput = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.descinput.setObjectName("descinput")
        self.desclayout.addWidget(self.descinput)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(add_coffee)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 150, 251, 22))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.pricelayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.pricelayout.setContentsMargins(0, 0, 0, 0)
        self.pricelayout.setObjectName("pricelayout")
        self.pricelabel = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.pricelabel.setObjectName("pricelabel")
        self.pricelayout.addWidget(self.pricelabel)
        self.priceinput = QtWidgets.QSpinBox(self.horizontalLayoutWidget_6)
        self.priceinput.setObjectName("priceinput")
        self.pricelayout.addWidget(self.priceinput)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(add_coffee)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(10, 170, 251, 22))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.valuelayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.valuelayout.setContentsMargins(0, 0, 0, 0)
        self.valuelayout.setObjectName("valuelayout")
        self.valuelabel = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.valuelabel.setObjectName("valuelabel")
        self.valuelayout.addWidget(self.valuelabel)
        self.valueinput = QtWidgets.QSpinBox(self.horizontalLayoutWidget_7)
        self.valueinput.setObjectName("valueinput")
        self.valuelayout.addWidget(self.valueinput)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(add_coffee)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 38, 166, 22))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.varietylayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.varietylayout.setContentsMargins(0, 0, 0, 0)
        self.varietylayout.setObjectName("varietylayout")
        self.Varietylabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.Varietylabel.setObjectName("Varietylabel")
        self.varietylayout.addWidget(self.Varietylabel)
        self.Varietyinput = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.Varietyinput.setObjectName("Varietyinput")
        self.varietylayout.addWidget(self.Varietyinput)
        self.horizontalLayoutWidget = QtWidgets.QWidget(add_coffee)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 171, 22))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.IDlayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.IDlayout.setContentsMargins(0, 0, 0, 0)
        self.IDlayout.setObjectName("IDlayout")
        self.IDlabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.IDlabel.setObjectName("IDlabel")
        self.IDlayout.addWidget(self.IDlabel)
        self.IDinput = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.IDinput.setObjectName("IDinput")
        self.IDlayout.addWidget(self.IDinput)
        self.savebtn = QtWidgets.QPushButton(add_coffee)
        self.savebtn.setGeometry(QtCore.QRect(310, 270, 75, 23))
        self.savebtn.setObjectName("savebtn")

        self.retranslateUi(add_coffee)
        QtCore.QMetaObject.connectSlotsByName(add_coffee)

    def retranslateUi(self, add_coffee):
        _translate = QtCore.QCoreApplication.translate
        add_coffee.setWindowTitle(_translate("add_coffee", "Form"))
        self.roastlabel.setText(_translate("add_coffee", "Степень прожарки"))
        self.seedlabel.setText(_translate("add_coffee", "В зернах?(1/0)"))
        self.desclabel.setText(_translate("add_coffee", "Описание"))
        self.pricelabel.setText(_translate("add_coffee", "Цена"))
        self.valuelabel.setText(_translate("add_coffee", "объем"))
        self.Varietylabel.setText(_translate("add_coffee", "Сорт"))
        self.IDlabel.setText(_translate("add_coffee", "ID"))
        self.savebtn.setText(_translate("add_coffee", "Сохранить"))


class Ui_DelWindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(328, 169)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 30, 311, 61))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(90, 130, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setGeometry(QtCore.QRect(40, 90, 100, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setGeometry(QtCore.QRect(190, 90, 100, 20))
        self.radioButton_2.setObjectName("radioButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Действительно хотите удалить данную запись?"))
        self.pushButton.setText(_translate("Dialog", "Подтвердить"))
        self.radioButton.setText(_translate("Dialog", "Да"))
        self.radioButton_2.setText(_translate("Dialog", "Нет"))
